// Code generated by tygo. DO NOT EDIT.
// Source of truth: internal/wire (Go). Regenerate with `go tool tygo generate`.
// Timestamps are RFC 3339 strings; see the package comment for the int64 rule.

//////////
// source: event.go

/**
 * EventType is the SSE event name. The client is a pure reducer over one
 * ordered log of these, so the set is additive-only: renaming one breaks every
 * tab that is still open across a restart.
 */
export const EventTypeSaveDetected = "save.detected";
export const EventTypeSaveParsing = "save.parsing";
export const EventTypeSaveRetry = "save.retry";
export const EventTypeSaveError = "save.error";
export const EventTypeSnapshotReady = "snapshot.ready";
export const EventTypeHealthLeg = "health.leg";
export const EventTypePlaythroughChanged = "playthrough.changed";
/**
 * EventTypeResync tells a client its cursor fell off the ring buffer: refetch
 * /api/state and the mounted views rather than trying to catch up.
 */
export const EventTypeResync = "resync";
export type EventType = typeof EventTypeSaveDetected | typeof EventTypeSaveParsing | typeof EventTypeSaveRetry | typeof EventTypeSaveError | typeof EventTypeSnapshotReady | typeof EventTypeHealthLeg | typeof EventTypePlaythroughChanged | typeof EventTypeResync;
/**
 * Envelope wraps every SSE payload. Seq is the process-monotonic sequence that
 * is also the SSE `id:` field, so a reconnecting client sends it back as
 * Last-Event-ID and the hub either replays from the 512-event ring or answers
 * with resync. Seq restarts at 1 on process start — it orders one connection's
 * stream, it is not a durable cursor.
 * Data is typed per Type: SaveMeta for the save.* events (save.error carries
 * SaveError), SnapshotMeta for snapshot.ready, LegHealth for health.leg,
 * PlaythroughChanged for playthrough.changed, and nothing for resync. The
 * client narrows it through a hand-kept discriminated union over these same
 * names — the generated types cannot express the correlation, so that union is
 * the one place the mapping is written twice, deliberately.
 */
export interface Envelope {
	seq: number /* int64 */;
	type: EventType;
	at: string;
	data?: any;
}

//////////
// source: state.go

/**
 * StateView is GET /api/state: everything a tab needs to draw itself from
 * nothing, and the thing it refetches after a resync.
 * It is a BOOTSTRAP, not a poll target. The board's steady state is the SSE
 * stream; this exists so that a tab opened mid-session, or reconnected after
 * the ring buffer moved past it, does not have to wait for the next save to
 * know anything.
 */
export interface StateView {
	build: BuildInfo;
	/**
	 * Vitals is the same body /api/views/vitals returns, inlined so first paint
	 * is one request.
	 */
	vitals: VitalsView;
	/**
	 * Snapshot describes the currently published parse; nil before the first
	 * one succeeds (the startup state, which is not an error).
	 */
	snapshot?: SnapshotMeta;
	watch: WatchHealth;
	/**
	 * LastEventSeq is the newest event the hub has issued. A client that
	 * bootstraps here and then subscribes with this as Last-Event-ID misses
	 * nothing in the gap between the two requests.
	 */
	last_event_seq: number /* int64 */;
	/**
	 * Silence is the design §6 two-stage timing, sent rather than hard-coded in
	 * the client so both halves of the contract move together.
	 */
	silence: SilencePolicy;
}
/**
 * BuildInfo identifies the binary a tab is talking to.
 * Hash is the versioning story (tech-design §2): assets and binary ship
 * together, so the only skew that can exist is a tab left open across a
 * restart. The client compares this against what it booted with and reloads on
 * a mismatch, which is cheaper than versioning every path.
 */
export interface BuildInfo {
	version: string;
	hash: string;
	/**
	 * SchemaVersion is the parser's snapshot schema; a save this build cannot
	 * read reports the schema_mismatch freshness state against it.
	 */
	schema_version: number /* int */;
	started_at: string;
	/**
	 * RSSBytes is the process's resident set, for the health drawer. 0 when the
	 * platform did not tell us — unknown, not "no memory".
	 */
	rss_bytes?: number /* int64 */;
}
/**
 * SilencePolicy is how long a client waits before disbelieving its stream
 * (design §6). The server heartbeats every HeartbeatS; two missed heartbeats
 * stale the freshness stamp, three mean the connection is gone.
 */
export interface SilencePolicy {
	heartbeat_s: number /* int */;
	stale_s: number /* int */;
	lost_s: number /* int */;
}
/**
 * WatchHealth is the watcher's own report: what it is watching, how often, and
 * what that has cost. It is the health drawer's watch section.
 */
export interface WatchHealth {
	dirs: string[];
	/**
	 * PollIntervalMS is the stat-poll period (D1: 2 s, one value, always).
	 */
	poll_interval_ms: number /* int64 */;
	detections: DetectionStats;
	/**
	 * Parses counts completed parses; Retries counts ErrSaveChanged retries
	 * across all of them; ParseErrors counts parses that ended in an error.
	 */
	parses: number /* int64 */;
	retries: number /* int64 */;
	parse_errors: number /* int64 */;
	median_parse_ms?: number /* int64 */;
	/**
	 * LastCheckAt is when the poll last ran. A poll that has stopped ticking is
	 * a board that has quietly stopped being live; this is how it shows.
	 */
	last_check_at?: string;
	last_detect_at?: string;
	cache: CacheHealth;
}
/**
 * DetectionStats counts detected saves and says what found each one. Manual is
 * kept apart from the poll for one reason: a player leaning on the refresh
 * button should not make the poll look like it is doing more work than it is.
 */
export interface DetectionStats {
	total: number /* int64 */;
	/**
	 * ByPoll is detections whose first sighting came from the ticker, which is
	 * every save the game writes on its own.
	 */
	by_poll: number /* int64 */;
	/**
	 * ByManual is detections whose first sighting came from a Kick — the
	 * refresh button or the refresh_save tool.
	 */
	by_manual: number /* int64 */;
}
/**
 * CacheHealth is the gob snapshot cache after the last GC pass.
 */
export interface CacheHealth {
	entries: number /* int */;
	bytes: number /* int64 */;
	/**
	 * Removed is entries deleted since start-up: stale schema versions at
	 * boot, then everything past the per-save keep count.
	 */
	removed: number /* int64 */;
}

//////////
// source: views.go

/**
 * VitalsView is /api/views/vitals: the empire sentence (design §4) as data.
 * Every optional pointer here means "unknown", which the client renders as the
 * dotted ∅ box — never as 0, never as blank.
 */
export interface VitalsView {
	freshness: Freshness;
	legs: LegHealth[];
	/**
	 * Credits is the player's balance; nil before the first successful parse.
	 */
	credits?: number /* int64 */;
	/**
	 * CreditsDelta is the change against the previous snapshot of the same
	 * playthrough; nil when there is no previous snapshot to compare against
	 * (first parse, or a playthrough switch reset the baseline).
	 */
	credits_delta?: number /* int64 */;
	/**
	 * CreditsSeries is the sparkline series, oldest first. Empty until the
	 * history store exists; the client draws its dotted-unknown empty state.
	 */
	credits_series?: CreditsSample[];
	counts: Counts;
	/**
	 * Wars is presence and offer counts only (v1): no phase words, no
	 * interpretation of who is winning.
	 */
	wars?: WarChip[];
}
/**
 * CreditsSample is one point of the credits sparkline.
 */
export interface CreditsSample {
	at: string;
	credits: number /* int64 */;
}
/**
 * Counts are the vitals tallies. They carry no severity: whether a count has
 * something new since the player last touched the board is client state (the
 * amber lifecycle, design §2), and the server has no way to know it.
 */
export interface Counts {
	fleet: number /* int */;
	stations: number /* int */;
	idle: number /* int */;
	/**
	 * Threats is a POINTER because this build cannot derive it at all: the
	 * knownto/attacker data arrives with the F3 schema bump (S6/F13a). A plain
	 * int would leave the board printing THREAT 0 at 22 px — "no one is hunting
	 * you", the 117-blueprints doctrine, from a field nobody computed. nil is
	 * absent on the wire and renders as the dotted ∅ box, which is the truth:
	 * unknown, not zero.
	 */
	threats?: number /* int */;
}
/**
 * WarChip is one faction pair currently at war, with how many war-related
 * mission offers back it. Faction ids are the game's own macro names ("argon",
 * "xenon"); the client owns the short forms it prints.
 */
export interface WarChip {
	faction_a: string;
	faction_b: string;
	offers: number /* int */;
}

//////////
// source: wire.go
/*
Package wire holds every JSON shape that crosses the browser boundary: the
SSE event envelope, the event payloads, and the view DTOs served from
/api/views/*. It is the single source of truth for the client's types —
tygo.yaml generates web/src/lib/types.gen.ts from this package, and CI fails
on drift, so a field renamed here without a regenerate is a red build.

Two rules keep this package honest.

Presentation-free. Views carry numbers, enums, and identifiers — never prose
written for a reader. Severity words, freshness copy, number grouping, and
glyphs all live in the client; the server says `state: "aging"` and
`credits: 12405882`, never "aging — 1 autosave overdue" or "12 405 882 Cr".
(The LLM-facing surfaces in internal/api do the opposite on purpose; do not
let those habits leak in here.)

int64 crosses as a string when it can exceed 2^53. JavaScript numbers are
float64: an integer above 9 007 199 254 740 991 silently loses its low bits
on JSON.parse. Any field whose domain reaches that far — cumulative ware
volumes, tick counters, anything unbounded — is declared `string` in Go with
the decimal digits, and the client parses it deliberately (BigInt or a
formatter that never does arithmetic). Fields that are provably smaller stay
int64: player credits are bounded by X4's own economy six orders of magnitude
below the limit, save sizes by the filesystem, parse durations by the clock.
When in doubt, string it — a rounded credit balance is a lie the board would
print at 34 px.
*/

/**
 * Leg is a subsystem the board reports liveness for. The save leg is the
 * watcher itself; the rest are homelab services the advisor leans on.
 */
export const LegSave = "save";
export const LegHum = "hum";
export const LegCanon = "canon";
export const LegRefrain = "refrain";
export type Leg = typeof LegSave | typeof LegHum | typeof LegCanon | typeof LegRefrain;
/**
 * LegHealth is one leg chip. Infrastructure is never red (design §2), so this
 * carries no severity: up/down plus the detail the health drawer shows.
 */
export interface LegHealth {
	leg: Leg;
	up: boolean;
	endpoint?: string;
	/**
	 * LastSeen is the last successful round trip; nil means never seen since
	 * start-up (unknown, which the client renders as such — not as "down long
	 * ago").
	 */
	last_seen?: string;
	last_round_trip_ms?: number /* int64 */;
	/**
	 * Detail is a short machine-ish reason ("connection refused", "404"), not a
	 * sentence written for the player.
	 */
	detail?: string;
}
/**
 * SaveKind is which of X4's three ways of writing a save produced this file.
 * The player thinks in these terms ("my last quicksave"), and the cadence the
 * freshness thresholds derive from is an AUTOSAVE cadence — a manual save every
 * half hour says nothing about whether autosave is on.
 */
export const SaveKindQuicksave = "quicksave";
export const SaveKindAutosave = "autosave";
export const SaveKindManual = "manual";
export type SaveKind = typeof SaveKindQuicksave | typeof SaveKindAutosave | typeof SaveKindManual;
/**
 * SaveMeta describes a savegame file as the watcher sees it — before any parse
 * has succeeded, so it holds nothing that requires reading the XML.
 */
export interface SaveMeta {
	path: string;
	/**
	 * Name is the file's base name without extension ("quicksave", "save_003"),
	 * which is what X4 players actually call a save.
	 */
	name: string;
	kind?: SaveKind;
	size_bytes: number /* int64 */;
	modified_at: string;
	/**
	 * AgeS is how old the file was when the server sent this, in seconds. The
	 * client counts up from ModifiedAt for the live stamp — a number the server
	 * wrote a minute ago is not an age — but it needs this once, because the two
	 * clocks are not the same clock: a LAN tab (or a tab on a machine whose time
	 * drifted) would otherwise render "in 4 minutes".
	 */
	age_s?: number /* int64 */;
	/**
	 * ParseMS is how long the parse of this save took; 0 before it has run.
	 */
	parse_ms?: number /* int64 */;
	/**
	 * Attempt is the retry counter on save.retry events (1-based); 0 elsewhere.
	 */
	attempt?: number /* int */;
}
/**
 * SnapshotMeta is what snapshot.ready carries: enough for the client to decide
 * whether to refetch its mounted views, plus the parse health the drawer shows.
 * It is never the snapshot itself — views are fetched, not pushed.
 */
export interface SnapshotMeta {
	/**
	 * GameGUID identifies the playthrough. A change here is a new empire: the
	 * diff baseline resets and nothing is compared across the boundary.
	 */
	game_guid: string;
	save: SaveMeta;
	schema_version: number /* int */;
	parsed_at: string;
	parse_ms: number /* int64 */;
	/**
	 * GameTimeS is in-game elapsed seconds. A regression means the player loaded
	 * an earlier save (design §6 rollback).
	 */
	game_time_s: number /* float64 */;
	save_date: string;
	game_version: string;
	player_name: string;
	/**
	 * Sections is the parse-health report: what came out of the save against
	 * the bands a healthy save of this playthrough produces.
	 */
	sections?: SectionHealth[];
	/**
	 * Rollback is set when GameTimeS went BACKWARDS within one playthrough: the
	 * player loaded an earlier save. The diff baseline is reset and loss alerts
	 * are suppressed, because everything that "disappeared" since the previous
	 * snapshot never happened.
	 */
	rollback?: boolean;
}
/**
 * SectionHealth is one parsed section's count measured against its expected
 * band. A section that falls out of band is how a silently-degraded parse gets
 * caught before it becomes a wrong number on the board.
 */
export interface SectionHealth {
	name: string;
	count: number /* int */;
	/**
	 * Low and High bound the expected count; both 0 means no band is known yet
	 * (a fresh playthrough), in which case InBand is meaningless and true.
	 */
	low: number /* int */;
	high: number /* int */;
	in_band: boolean;
}
/**
 * FreshnessState is the design §6 state machine, exactly. The copy for each
 * state lives in the client; the server only decides which one is true.
 */
export const FreshnessStateStartup = "startup";
export const FreshnessStateParsing = "parsing";
export const FreshnessStateRetrying = "retrying";
export const FreshnessStateCurrent = "current";
export const FreshnessStateAging = "aging";
export const FreshnessStateStale = "stale";
export const FreshnessStateRollback = "rollback";
export const FreshnessStateParseError = "parse_error";
export const FreshnessStateSchemaMismatch = "schema_mismatch";
export type FreshnessState = typeof FreshnessStateStartup | typeof FreshnessStateParsing | typeof FreshnessStateRetrying | typeof FreshnessStateCurrent | typeof FreshnessStateAging | typeof FreshnessStateStale | typeof FreshnessStateRollback | typeof FreshnessStateParseError | typeof FreshnessStateSchemaMismatch;
/**
 * Freshness is the vitals freshness block. The two connection-lost stages are
 * deliberately absent: only the client can know the stream went quiet, so it
 * derives those from SSE silence and overrides what it last heard here.
 */
export interface Freshness {
	state: FreshnessState;
	/**
	 * WatchDirs is what the startup state names ("watching <dir>") and what the
	 * health drawer lists.
	 */
	watch_dirs: string[];
	/**
	 * Save is the save this state is about; nil in startup, when there is none.
	 */
	save?: SaveMeta;
	parsed_at?: string;
	parse_ms?: number /* int64 */;
	/**
	 * MedianParseMS is the rolling median the parsing progress blocks step
	 * against; 0 until enough parses have been observed to have one.
	 */
	median_parse_ms?: number /* int64 */;
	/**
	 * Attempt is the retry counter while State is retrying.
	 */
	attempt?: number /* int */;
	/**
	 * AutosavesOverdue drives the aging and stale thresholds, derived from this
	 * playthrough's observed save cadence rather than a constant.
	 */
	autosaves_overdue?: number /* int */;
	/**
	 * Error is set for the parse_error and schema_mismatch states.
	 */
	error?: SaveError;
}
/**
 * SaveErrorKind distinguishes "this save did not parse" from "this build cannot
 * parse this game version" — the same amber, very different player action.
 */
export const SaveErrorKindParse = "parse";
export const SaveErrorKindSchema = "schema";
export type SaveErrorKind = typeof SaveErrorKindParse | typeof SaveErrorKindSchema;
/**
 * SaveError is the save.error payload and the freshness block's error detail.
 */
export interface SaveError {
	kind: SaveErrorKind;
	/**
	 * Detail is the underlying error text for the health drawer, verbatim. The
	 * lane row's copy is written by the client.
	 */
	detail: string;
	save?: SaveMeta;
}
/**
 * PlaythroughChanged is emitted when the save's GameGUID changes: every
 * baseline resets and no diff crosses the boundary.
 */
export interface PlaythroughChanged {
	game_guid: string;
	/**
	 * Label is the save's own name for the playthrough (player name / start), a
	 * game-authored string, not composed prose.
	 */
	label?: string;
}
