// Command replay is the S7 rule-mining and replay harness.
//
// It runs an archive of savegames through internal/logbook, internal/diff and
// internal/rules and reports what they would have done, so that a rule table
// can carry a MEASURED number instead of a hoped-for one.
//
// Three modes:
//
//	-census        template census over every logbook in the archive
//	-tsv FILE      dump every distinct logbook event as TSV (implies -census)
//	-replay        diff consecutive saves and measure every rule
//
// Usage:
//
//	X4MCP_CACHE_DIR=~/.cache/x4mcp-corpus \
//	  nice -n 19 ionice -c 3 go run ./scripts/replay -dir ~/x4-save-archive -census
//
//	X4MCP_CACHE_DIR=~/.cache/x4mcp-corpus \
//	  nice -n 19 ionice -c 3 go run ./scripts/replay -dir ~/x4-save-archive -replay
//
// The first run over a cold cache parses every save (~12 s each, so ~40 min for
// 200) and writes ~730 MB of snapshots into X4MCP_CACHE_DIR; every run after
// that is seconds. Point the cache somewhere with room, and NOT at the default
// ~/.cache/x4mcp, which the live server shares.
//
// # It is read-only, and it checks
//
// The archive is irreplaceable and the live save directory is the player's
// game. This command opens saves O_RDONLY through the same loader the server
// uses, writes only to stdout and to the file named by -tsv, and refuses
// outright to run against a directory inside a discovered X4 save root.
//
// # Privacy
//
// The output is meant to be pasted into a public repo. It never prints the
// player name, the profile id, the playthrough GUID or the seed: playthroughs
// are numbered, and the identifiers that do appear (registration codes like
// MUG-920, sector names, hull names) are generated by the game.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/signal"
	"sort"
	"strings"
	"syscall"
	"text/tabwriter"

	"github.com/pequalsnp/x4mcp/internal/diff"
	"github.com/pequalsnp/x4mcp/internal/logbook"
	"github.com/pequalsnp/x4mcp/internal/replay"
	"github.com/pequalsnp/x4mcp/internal/x4data"
)

func main() {
	var (
		dir      = flag.String("dir", defaultArchive(), "archive directory of *.xml.gz saves (read-only)")
		gameDir  = flag.String("game", "", "X4 install dir (default: auto-detect / X4MCP_GAME_DIR)")
		census   = flag.Bool("census", false, "logbook template census")
		tsv      = flag.String("tsv", "", "write every distinct logbook event to this TSV file (implies -census)")
		doReplay = flag.Bool("replay", false, "diff consecutive saves and measure every rule")
		limit    = flag.Int("limit", 0, "use only the newest N saves (0 = all)")
		top      = flag.Int("top", 40, "rows to show in census tables")
		asJSON   = flag.Bool("json", false, "emit the report as JSON")
		fires    = flag.String("fires", "", "with -replay: also write every individual fire as JSON to this file")
		quiet    = flag.Bool("quiet", false, "no progress on stderr")
	)
	flag.Parse()

	if *tsv != "" {
		*census = true
	}
	if !*census && !*doReplay {
		fmt.Fprintln(os.Stderr, "pick a mode: -census, -tsv FILE, or -replay")
		flag.Usage()
		os.Exit(2)
	}
	if *dir == "" {
		fmt.Fprintln(os.Stderr, "no -dir given and no archive found")
		os.Exit(2)
	}
	if err := replay.ReadOnly(*dir); err != nil {
		fmt.Fprintln(os.Stderr, "refusing:", err)
		os.Exit(1)
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	db := x4data.LoadTextDB(*gameDir)
	if db.Size() == 0 {
		fmt.Fprintln(os.Stderr,
			"warning: no X4 install found, so the template catalog is EMPTY —",
			"every logbook signal will be missing and every corroboration will fall back to one group.")
	}

	progress := func(stage string, i, n int, name string) {
		if *quiet {
			return
		}
		fmt.Fprintf(os.Stderr, "\r%-7s %4d/%4d  %-56s", stage, i, n, name)
		if i == n {
			fmt.Fprintln(os.Stderr)
		}
	}

	if *census {
		var out *os.File
		if *tsv != "" {
			f, err := os.Create(*tsv)
			if err != nil {
				fmt.Fprintln(os.Stderr, err)
				os.Exit(1)
			}
			defer f.Close()
			out = f
		}
		copts := replay.CensusOptions{Dir: *dir, Limit: *limit, Top: *top, Progress: progress}
		if names, err := x4data.LoadSectorNames(*gameDir); err == nil {
			for _, n := range names {
				copts.SectorNames = append(copts.SectorNames, n)
			}
		}
		if out != nil {
			copts.TSV = out
		}
		c, err := replay.RunCensus(ctx, db, copts)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if *asJSON {
			emitJSON(c)
		} else {
			printCensus(os.Stdout, c)
		}
	}

	if *doReplay {
		opts := diff.DefaultOptions()
		opts.Catalog = logbook.NewCatalog(db, logbook.RulePages()...)
		rep, err := replay.Run(ctx, replay.Options{Dir: *dir, Limit: *limit, Diff: opts, Progress: progress})
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if *fires != "" {
			b, _ := json.MarshalIndent(rep.Fires, "", "  ")
			if err := os.WriteFile(*fires, b, 0o644); err != nil {
				fmt.Fprintln(os.Stderr, err)
			}
		}
		if *asJSON {
			emitJSON(rep)
		} else {
			printReplay(os.Stdout, rep)
		}
	}
}

func defaultArchive() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	d := home + "/x4-save-archive"
	if fi, err := os.Stat(d); err == nil && fi.IsDir() {
		return d
	}
	return ""
}

func emitJSON(v any) {
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	_ = enc.Encode(v)
}

func printCensus(w *os.File, c *replay.Census) {
	fmt.Fprintf(w, "\n== LOGBOOK CENSUS ==\n")
	fmt.Fprintf(w, "saves scanned            %d\n", c.SavesScanned)
	fmt.Fprintf(w, "log rows                 %d  (X4's <log> is cumulative; a row is one save's copy of an event)\n", c.TotalRows)
	fmt.Fprintf(w, "distinct events          %d\n", c.DistinctLog)
	fmt.Fprintf(w, "  uncategorized          %d\n", c.Uncategorized)
	fmt.Fprintf(w, "catalog templates        %d compiled, %d skipped (too little literal text to index)\n",
		c.CatalogTemplates, c.CatalogSkipped)
	fmt.Fprintf(w, "masker vocabulary        %d names\n", c.VocabularySize)
	fmt.Fprintln(w)
	fmt.Fprintf(w, "matched a game template  %d / %d  (%.1f%%) across %d distinct {page,id}\n",
		c.Matched, c.DistinctLog, pct(c.Matched, c.DistinctLog), c.MatchedRefs)
	fmt.Fprintf(w, "  of which ambiguous     %d  (another template scored the same; the ref shown is a tie-break)\n", c.AmbiguousHits)
	fmt.Fprintf(w, "classified by RuleRefs   %d / %d  (%.1f%%)  — the ordered table a rule actually keys on\n",
		c.RuleClassified, c.DistinctLog, pct(c.RuleClassified, c.DistinctLog))
	fmt.Fprintf(w, "unmatched                %d  collapsing to %d masked signatures\n",
		c.Unmatched, c.UnmatchedSignature)

	fmt.Fprintf(w, "\n-- by category --\n")
	printCounts(w, c.ByCategory)

	fmt.Fprintf(w, "\n-- by rule event kind --\n")
	printCounts(w, c.ByEventKind)

	fmt.Fprintf(w, "\n-- by page --\n")
	printCounts(w, c.ByPage)

	fmt.Fprintf(w, "\n-- top templates --\n")
	printRows(w, c.TopRefs)

	fmt.Fprintf(w, "\n-- top unmatched signatures --\n")
	printRows(w, c.TopSignatures)
}

func printRows(w *os.File, rows []replay.CensusRow) {
	tw := tabwriter.NewWriter(w, 0, 0, 2, ' ', 0)
	fmt.Fprintln(tw, "events\trows\tkey\ttemplate / masked residue\texample")
	for _, r := range rows {
		fmt.Fprintf(tw, "%d\t%d\t%s\t%s\t%s\n",
			r.Events, r.Rows, r.Key, clip(r.Template, 64), clip(r.Example, 72))
	}
	tw.Flush()
}

func printCounts(w *os.File, m map[string]int) {
	type kv struct {
		k string
		n int
	}
	var rows []kv
	for k, n := range m {
		rows = append(rows, kv{k, n})
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].n != rows[j].n {
			return rows[i].n > rows[j].n
		}
		return rows[i].k < rows[j].k
	})
	tw := tabwriter.NewWriter(w, 0, 0, 2, ' ', 0)
	for _, r := range rows {
		fmt.Fprintf(tw, "  %-32s\t%d\n", r.k, r.n)
	}
	tw.Flush()
}

func printReplay(w *os.File, rep *replay.Report) {
	fmt.Fprintf(w, "\n== REPLAY ==\n")
	fmt.Fprintf(w, "archive                  %s\n", rep.Dir)
	fmt.Fprintf(w, "saves                    %d  (%d failed to parse)\n", len(rep.Saves), rep.ParseErrors)
	if rep.ReloadErrors > 0 {
		fmt.Fprintf(w, "  NOT re-read for diffing %d  (indexed, then gone — the archive rolled mid-run; see anomalies)\n",
			rep.ReloadErrors)
	}
	for _, p := range rep.Playthroughs {
		fmt.Fprintf(w, "playthrough %d            %d saves, %.1f in-game hours, %.1f real days\n",
			p.Play, p.Saves, (p.LastTime-p.FirstTime)/3600, float64(p.LastDate-p.FirstDate)/86400)
	}
	fmt.Fprintf(w, "pairs                    %d attempted, %d diffed\n", rep.Pairs, rep.Diffed)
	if len(rep.Refusals) > 0 {
		fmt.Fprintf(w, "refused\n")
		printCounts(w, rep.Refusals)
	}
	fmt.Fprintf(w, "covered                  %.1f in-game hours over %.1f real days\n",
		rep.ElapsedS/3600, rep.RealDays)
	for _, a := range rep.Anomalies {
		fmt.Fprintf(w, "anomaly                  %s\n", a)
	}

	fmt.Fprintf(w, "\n-- logbook windows --\n")
	fmt.Fprintf(w, "  entries in windows     %d\n", rep.Logbook.WindowEntries)
	fmt.Fprintf(w, "  classified by RuleRefs %d  (%.1f%%)\n",
		rep.Logbook.WindowClassified, pct(rep.Logbook.WindowClassified, rep.Logbook.WindowEntries))
	fmt.Fprintf(w, "  destroy sentences      %d — %d carried no code, %d named a code no player asset had\n",
		rep.Logbook.DestroyEntries, rep.Logbook.DestroyNoCode, rep.Logbook.DestroyUnmatched)
	printCounts(w, rep.Logbook.ByEventKind)

	fmt.Fprintf(w, "\n-- per rule --\n")
	tw := tabwriter.NewWriter(w, 0, 0, 2, ' ', 0)
	fmt.Fprintln(tw, "kind\tfires\t/real day\t/game hr\tsubjects\tcorrob\tuncorrob\tfalsified\tgroups")
	for _, k := range rep.ByKind {
		perDay, perHour := 0.0, 0.0
		if rep.RealDays > 0 {
			perDay = float64(k.Fires) / rep.RealDays
		}
		if rep.ElapsedS > 0 {
			perHour = float64(k.Fires) / (rep.ElapsedS / 3600)
		}
		fmt.Fprintf(tw, "%s\t%d\t%.2f\t%.2f\t%d\t%d\t%d\t%d\t%s\n",
			k.Kind, k.Fires, perDay, perHour, k.Subjects,
			k.Corroborated, k.Uncorroborated, k.Falsified, combos(k.GroupCombos))
	}
	tw.Flush()

	fmt.Fprintf(w, "\n-- what the rules layer would have emitted --\n")
	fmt.Fprintf(w, "   (an ALERT is one dedupe key: what a player is actually shown)\n")
	tw = tabwriter.NewWriter(w, 0, 0, 2, ' ', 0)
	fmt.Fprintln(tw, "rule\ton\tdeclared\tconfidence\tfires\talerts\tred\tamber\tgrey\tconflict\tdowngrade\tred alerts/wk\talerts/day")
	for _, r := range rep.ByRule {
		fmt.Fprintf(tw, "%s\t%v\t%s\t%s\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%.2f\t%.2f\n",
			r.RuleID, r.Enabled, r.Declared, r.Confidence, r.Fires, r.Alerts,
			r.Red, r.Amber, r.Grey, r.Conflicts, r.Downgrades, r.RedPerWeek, r.AlertsPerDay)
	}
	tw.Flush()

	if n := countFalsified(rep); n > 0 {
		fmt.Fprintf(w, "\n-- falsified by the corpus itself --\n")
		for _, f := range rep.Fires {
			if f.Falsified == "" {
				continue
			}
			fmt.Fprintf(w, "  %-14s %-10s %s — %s\n", f.Kind, f.Subject, f.SaveName, f.Falsified)
		}
	}
}

func countFalsified(rep *replay.Report) int {
	n := 0
	for _, f := range rep.Fires {
		if f.Falsified != "" {
			n++
		}
	}
	return n
}

func combos(m map[string]int) string {
	type kv struct {
		k string
		n int
	}
	var rows []kv
	for k, n := range m {
		rows = append(rows, kv{k, n})
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].n != rows[j].n {
			return rows[i].n > rows[j].n
		}
		return rows[i].k < rows[j].k
	})
	var parts []string
	for _, r := range rows {
		parts = append(parts, fmt.Sprintf("%s=%d", r.k, r.n))
	}
	return strings.Join(parts, " ")
}

func pct(a, b int) float64 {
	if b == 0 {
		return 0
	}
	return 100 * float64(a) / float64(b)
}

func clip(s string, n int) string {
	s = strings.ReplaceAll(s, "\n", " / ")
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}
